import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import { Montserrat } from 'next/font/google';
import BootstrapClient from '@/components/BootstrapClient.js';

const inter = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <BootstrapClient />
      </body>
    </html>
  )
}
